modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="armedlogistics" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Armed Logistics" #mandatory
authors="Ourten"
description='''Logistic System mod with robotic Arms'''

[[dependencies.armedlogistics]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.armedlogistics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,1.15)"
    ordering="NONE"
    side="BOTH"